# Generated by Django 4.2.7 on 2023-11-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Economics'), ('SC', 'Science'), ('SP', 'Sport'), ('P', 'Policy'), ('H', 'Health'), ('T', 'Travel')], max_length=20, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
