# Generated by Django 4.2.7 on 2023-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0005_alter_article_options_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Экономика', 'Economics'), ('Наука', 'Science'), ('Спорт', 'Sport'), ('Политика', 'Policy'), ('Здоровье', 'Health'), ('Путешествия', 'Travel')], max_length=20, verbose_name='Категории'),
        ),
    ]
