# Generated by Django 4.2.7 on 2023-12-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news1', '0009_viewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
